databases:
  - name: lms-db
    plan: free
    region: ohio
    databaseName: lmsdb
    user: lmsadmin

services:
  # 2. Backend (Spring Boot Docker)
  - type: web
    name: lms-backend
    env: docker
    plan: free
    region: ohio
    rootDir: backend
    envVars:
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: lms-db
          property: connectionString
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: lms-db
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: lms-db
          property: password
      - key: HIBERNATE_DIALECT
        value: org.hibernate.dialect.PostgreSQLDialect
      - key: SPRING_DATASOURCE_DRIVER
        value: org.postgresql.Driver
      - key: FRONTEND_URL
        fromService:
          type: web
          name: lms-frontend
          property: host

  # 3. Frontend (Static Site)
  - type: static
    name: lms-frontend
    plan: free
    region: ohio
    rootDir: frontend
    buildCommand: npm install && npm run build
    publishDir: dist
    envVars:
      - key: VITE_API_BASE_URL
        fromService:
          type: web
          name: lms-backend
          property: host
        suffix: /api
